### PR TITLE
Travis deploy

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
Assuming I did everything correctly, and after merging this, creating git tag 1.1.0 should result in a release on pypi.

**Review by rousseldenis — APPROVED** [review]
Seems great

**Comment by guewen** [comment]
Great, it reminds me that I wanted to do it for pytest-odoo since some time, so I did the same here: https://github.com/camptocamp/pytest-odoo/pull/28 :)

**Comment by sbidoul** [comment]
@guewen @rousseldenis I added `setup.cfg` so as to generate universal wheels that work with py2 and py3.

**Pull request merged**
