### PR TITLE
[IMP] Rename package for PEP-8 compliance

### PR DESCRIPTION
**Pull request by lasley**
* Rename `odoosentinel` package to `odoo_sentinel` for PEP-8 compliance

### CODE REVIEW

**Comment by Garamotte** [comment]
Thanks, I removed the `-`, but replacing it by an `_` is better :)

If I'm not wrong, you forgot to update the setup.py file.

**Comment by lasley** [comment]
> If I'm not wrong, you forgot to update the setup.py file.

You're not wrong. Updated!

**Review by Garamotte — APPROVED** [review]
Thanks :)

**Comment by lasley** [comment]
I'm merging this one without the proper amount of reviews. The longer the incorrect package name is in the wild, the worse the problem becomes.

**Pull request merged**
